% kv_d01read Read data from .d01/.exp SpecMan data files
%
%   data = kv_smtdmsread(filename,...)
%   [ax,data] = kv_smtdmsread(filename,...);
%   [ax,data,dsc] = kv_smtdmsread(filename,...);
%
%   Reads data and axis information from tdms file generated by
%   SpecMan4EPR

% KAZAN dataviewer with plugins By Boris Epel & Alexey Silakov
% MPI of Bioinorganic Chemistry, Muelheim an der Ruhr, 2003
% Free for non-commercial use. Use the program at your own risk. 
% The authors retains all rights. 
% Contact: epel@mpi-muelheim.mpg.de


function varargout=kv3_smtdmsread(filename, varargin)

exp = kv3_LoadTDMS(filename);

% cycle for streams
Streams{1} = TDMS_StreamToArray(exp.streams.Re);
Streams{2} = TDMS_StreamToArray(exp.streams.Im);
spec = Streams{1} + 1i* Streams{2};
        
ax = kv3_SpecManTDMSpar(exp);

allstreams = fieldnames(exp.streams);
ax.raw = [];
for ii=1:length(allstreams)
  ax.raw(:,:,ii) = TDMS_StreamToArray(exp.streams.(allstreams{ii}));
end

if ~isfield(ax, 'x') || size(ax.x, 1)~=size(spec, 1)
  ax.x = 1:size(Streams{1}, 1);
end
ax.type = 'data';
if isfield(exp.root,'freq1')
    ax.freq1 = kv3_getvalue(dsc.general_freq1);
end

% assign output depending on number of output arguments
% requested
switch nargout
 case 1
   varargout = {spec};
 case 2
   varargout = {ax, spec};
 case 3
   copy_sections = {'axis', 'params','exp_info','sample_info','devices'};
   for jj = 1:length(copy_sections)
     if ~isfield(exp, copy_sections{jj}) || isempty(exp.(copy_sections{jj}))
       disp(['WARNING: Field ',copy_sections{jj},' is not present'])
       continue; 
     end
     fld = fieldnames(exp.(copy_sections{jj}));
     for ii=1:length(fld)
       exp.root.([copy_sections{jj},'_',fld{ii}]) = exp.(copy_sections{jj}).(fld{ii});
     end
   end
   exp.root.KAZANformat = 'SPECMANTDMS';

   varargout = {ax, spec, exp.root};
end
% --------------------------------------------------------------------
function the_set = convert_property(the_set, the_entry, the_prefix)
for ii=1:length(the_entry)
  new_name = [the_prefix,the_entry(ii).Name];
  
  the_set.(validMLfield(new_name)) = the_entry(ii).Value;
end

% --------------------------------------------------------------------
function str = validMLfield(str)
symbols_to_kill = '/.[]?@#$():''-';
for ii=1:length(symbols_to_kill), str(str==symbols_to_kill(ii)) = []; end % remove symbols
str(str==' ') = '_'; % convert spaces into underscores
if isempty(str), str = 'Fempty'; 
elseif contains('0123456789', str(1)), str = ['F',str];
end
str = str(:)';

% --------------------------------------------------------------------
function data = TDMS_StreamToArray(array)

max_dim = double([array.dim1, array.dim2, array.dim3, array.dim4]);

total_data = prod(max_dim);

data_size = length(array.data{1});

% Find if data are indded multiple copies of the same set
one_set = total_data / data_size; 
n_rep = fix(length(array.data) / one_set);

data = zeros(prod(max_dim)/one_set, one_set);
for ii=1:one_set
  data(:, ii) = array.data{ii};
end

if n_rep > 1
  for jj = 2:n_rep
    for ii=1:one_set
      data(:, ii) = data(:, ii) + array.data{ii+one_set*(jj-1)};
    end
    data(:, ii) = data(:, ii) / n_rep;
  end
end

data = reshape(data, max_dim);
